### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by Benn7752** [Xerosigma/BLPAndroidTeam#5]
Do we need a logout button? how does someone close the app

**Comment by cadeauxramon603** [comment]
hmm had not thought about this function. i suppose that we cold do that but whats the use case and how does that affect the way people use the app

**Comment by Xerosigma** [comment]
Logout is usually tied to states and sessions which we currently do not have. Currently "signing in" only allows access to content. Simply hard closing the app will require the user to input the password again. I'd say discuss internally why this functionality would be important. State handling is never trivial.

**Comment by cadeauxramon603** [comment]
closing this issue as we have decided not to go down this route
