### ISSUE TITLE
Generate "SYF" Ticker Symbol Live on Announcements Page

### ISSUE THREAD

**Issue by sptucha** [Xerosigma/BLPAndroidTeam#8]
Somehow leverage an API to have the live quote for Synchrony's stock on the announcement page.

**Comment by Xerosigma** [comment]
@sptucha we can do this with a WebView that displays a website with the quote. WebViews can essentially act as nested browsers. Do you have a sample web address I can see?

**Comment by sptucha** [comment]
https://www.google.com/finance?q=Syf&ei=bQNvVokng46YAYevm_AD

Something like this?

**Comment by sptucha** [comment]
So we got a Web view to work, but it displays the whole page, we are just
looking for the stock quote

**Comment by Xerosigma** [comment]
Great. That's a good start. If you add the HTML Div tag id to the end of the URL - the WebView should navigate directly to said section (notice "#price-panel" at the end):

https://www.google.com/finance?q=Syf&ei=bQNvVokng46YAYevm_AD#price-panel

There may be a way to kill scroll functionality on the WebView so it only shows this div tag.

P.S. will ponder alterative methods.

**Comment by Xerosigma** [comment]
@sptucha @cadeauxramon603 the only other ways I'm seeing this happening is parse the pages HTML for the quote OR find a free API that will let you pull quotes down as simple values. May be a bit tricky.

**Comment by cadeauxramon603** [comment]
@sptucha  you should will lead this effort, if you want it give it a try and i will help in whatever way you want me to

**Comment by sptucha** [comment]
The html shows it in a <span> tag and the value assigned to it just keeps
changing, not sure where that value is coming from

**Comment by cadeauxramon603** [comment]
@sptucha i think this might be easier to try and get a free lib (like the gson stuff) that will easily dot his for us. writing the code to search it could get problematic. @Xerosigma do you know a place we can search for different packages to look at what libs we might want to use (besides the obvious google search)

**Comment by Xerosigma** [comment]
@sptucha @cadeauxramon603 this is NOT in JSON format BUT it's live and parseable:

http://www.google.com/finance/info?q=NYSE:SYF

**Comment by sptucha** [comment]
Is that a live update?

**Comment by cadeauxramon603** [comment]
It is live and parsable now to figure out how to use it

**Comment by Xerosigma** [comment]
@cadeauxramon603 @sptucha if you remove the leading "// " we may be able to parse it as a JSON array.

**Comment by cadeauxramon603** [comment]
#blessed #crispy

**Comment by sptucha** [comment]
Currently I'm trying to read a URL, from here I was going to read the link
you sent me and have it search for the ticker price

**Comment by cadeauxramon603** [comment]
leverage the Service Handler file.. line 129+ in Tabs fragment show how to do this

**Comment by sptucha** [comment]
This shit isn't possible I'm out

**Comment by Xerosigma** [comment]
This feature has been implemented.

**Comment by sptucha** [comment]
Just pulled, shits crisssssspy

**Comment by Xerosigma** [comment]
Haha yea it's pretty crispy.

**Comment by sptucha** [comment]
It doesn't work on the emulator on our network, but off network and on my
galaxy it works

**Comment by Xerosigma** [comment]
Likely due to SyFi proxy
